### ISSUE TITLE
Chart text fields get cut off -- update mermaid-cli release?

### ISSUE THREAD

**Issue by dantrim** [matthewfeickert/mermaid-CLI#3]
Using this, some formatted text gets cut. However, installing a local version of `mmdc` it does not cut off the text. Perhaps an update of the mermaid-cli release is needed?

**Comment by matthewfeickert** [comment]
@dantrim Thanks for the Issue. Can you also post the example code that is getting cut?

**Comment by dantrim** [comment]
The example diagram (`test_file.mmd`) is here:
```
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[fa:fa-car Car]
```
Running it like:
```
docker run --rm -v ${PWD}:/home/node/data matthewfeickert/mermaid-cli:latest -i test_file.mmd -o test.pdf
```
results in
<img width="470" alt="image" src="https://user-images.githubusercontent.com/7841565/103014633-f39fa600-44f3-11eb-875d-4043ffa28212.png">

Whereas running through either the [live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdIiwibWVybWFpZCI6e30sInVwZGF0ZUVkaXRvciI6ZmFsc2V9) I see:
![image](https://user-images.githubusercontent.com/7841565/103014813-3f524f80-44f4-11eb-85eb-8bc43d66cb5f.png)

**Comment by matthewfeickert** [comment]
@dantrim I've got some good/bad news for you.

**The good news:**

In looking into this problem more I learned there is now a [`mermaid-js` GitHub org](https://github.com/mermaid-js) with a [`mermaid-js/mermaid-cli`](https://github.com/mermaid-js/mermaid-cli) project that has a Docker image. This means that my shoddy project is no longer needed, and it can be deprecated! This is my first time deprecating a project of mine on GitHub so I'm quite excited to get to kill off software. :) Thanks!

**The bad news:**

The official Docker image doesn't solve your issue either. :disappointed: 

If I take your file and run

```
$ docker pull minlag/mermaid-cli:8.8.4
$ docker run --rm --user 1000:1000 -v $PWD:/data minlag/mermaid-cli:8.8.4 --pdfFit -i test_file.mmd -o test.pdf
$ docker run --rm --user 1000:1000 -v $PWD:/data minlag/mermaid-cli:8.8.4 -i test_file.mmd -o test.png
```

I get the attached images

![test](https://user-images.githubusercontent.com/5142394/103067671-0e6c2c00-4581-11eb-83f9-567bf3bafc19.png)

[test.pdf](https://github.com/matthewfeickert/mermaid-CLI/files/5738479/test.pdf)

which while better than your original are still chopping off the car.

As I'm unable to give you a solution with either my (now deprecated) image or the official image I'm going to suggest that you open this Issue up over on https://github.com/mermaid-js/mermaid-cli and point to this Issue for reference. I'd like to request that you also tag me in the new Issue so I can follow along. It seems that https://github.com/mermaid-js/mermaid-cli/issues/85 may be related, so I'd give that a read first.

Please let me know if you find this to be a suitable solution.
